language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - npm run build
  - firebase deploy --project covid-19-270712 --token $FIREBASE_TOKEN
